from typing import Final


TEAM_NAME_GFORM_HEADER: Final = 'Team Name'
PLAYER_NAME_GFORM_HEADER: Final = 'Player {}\'s Splashtag'
PLAYER_DISCORD_GFORM_HEADER: Final = 'Player {}\'s Discord Username'

TEAM_NAME_BATTLEFY_HEADER: Final = 'teamName'
PLAYER_NAME_BATTLEFY_HEADER: Final = 'inGameName'
PLAYER_DISCORD_BATTLEFY_HEADER: Final = 'Captain\'s Discord username'

TEAM_NAME_SENDOU_HEADER: Final = 'TEAM_NAME'
CAPTAIN_NAME_SENDOU_HEADER: Final = 'CAPTAIN_USERNAME'
CAPTAIN_DISCORD_SENDOU_HEADER: Final = 'CAPTAIN_DISCORD'
PLAYER_NAME_SENDOU_HEADER: Final = 'PLAYER_USERNAME'
PLAYER_DISCORD_SENDOU_HEADER: Final = 'PLAYER_DISCORD'